name: Docker Publish (Production Images)

on:
  workflow_dispatch:
  release:
    types: [released]
  schedule:
    - cron: "0 8 * * 2" # Every Tuesday at 8:00 AM UTC

jobs:
  fullstack-cli:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: fullstack-cli
      checkout-type: latest-stable
    secrets: inherit
  fullstack-fpm:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: fullstack-fpm
      checkout-type: latest-stable
    secrets: inherit
  fullstack-http:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: fullstack-http
      checkout-type: latest-stable
    secrets: inherit
  franken:
    uses: ./.github/workflows/service_docker-build-and-publish-franken.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: franken
      checkout-type: latest-stable
    secrets: inherit
