name: Docker Publish (Production Images)

on:
  workflow_dispatch:
  release:
    types: [released]
  schedule:
    - cron: "0 8 * * 2"

jobs:
  cli-alpine:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: cli-alpine
      checkout-type: latest-stable
    secrets: inherit
  laravel:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: laravel
      checkout-type: latest-stable
    secrets: inherit
  laravel-dev:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: laravel-dev
      checkout-type: latest-stable
    secrets: inherit
  smart:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: smart
      checkout-type: latest-stable
    secrets: inherit
  multi-stage:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ""
      tag-prefix: ""
      php-variation: multi-stage
      checkout-type: latest-stable
    secrets: inherit
