name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
  schedule:
    - cron: "0 8 * * 1" # Every Monday at 8:00 AM UTC

jobs:
  fullstack-cli:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: "beta-"
      tag-prefix: "beta-"
      php-variation: fullstack-cli
      checkout-type: branch
    secrets: inherit
  fullstack-fpm:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: "beta-"
      tag-prefix: "beta-"
      php-variation: fullstack-fpm
      checkout-type: branch
    secrets: inherit
  fullstack-http:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: "beta-"
      tag-prefix: "beta-"
      php-variation: fullstack-http
      checkout-type: branch
    secrets: inherit
