name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
  schedule:
    - cron: "0 8 * * 1"

jobs:
  laravel:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: "beta-"
      tag-prefix: "beta-"
      php-variation: laravel
      checkout-type: branch
    secrets: inherit
  laravel-dev:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: "beta-"
      tag-prefix: "beta-"
      php-variation: laravel-dev
      checkout-type: branch
    secrets: inherit
